services:
  - type: web
    name: properties-in-israel-frontend
    env: static
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html